### ISSUE TITLE
Application tool-tips do not disappear correctly

### ISSUE THREAD

**Issue by Tzaphkiel** [ecbsdmx/milliws#18]
Some application tool-tips do not disappear when changing views.

See the examples below:
![capture](https://cloud.githubusercontent.com/assets/644489/12727048/3bfc437c-c91b-11e5-8544-1efa842ca10f.PNG)

![capture](https://cloud.githubusercontent.com/assets/644489/12727072/6806d2a2-c91b-11e5-86b9-1ad0c5af902f.PNG)

**Comment by sosna** [comment]
Check if adding the trigger property is sufficient.

**Comment by Tzaphkiel** [comment]
Pull request #30 fixes the issue with the general tooltips. It does not fix the calendar heatmap tooltips as they use D3 instead.
A solution might involve not using D3 for the tooltips but rather have the same approach as for the other application tooltips. This will soon be tested.
