### ISSUE TITLE
Exception - TypeError : Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by Tzaphkiel** [ecbsdmx/milliws#7]
In the VPS service logs for MilliWS we can see the following exception occurring when events are recorded:
```
    milliws[28093]: Exception in callback of async function: TypeError: Cannot read property 'statusCode' of undefined
    milliws[28093]: at app/server/scheduler.js:104:33
    milliws[28093]: at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

  * occurs at the same time as the ```dexr-comp``` job appearing in red in the table
  * of size : ```62 bytes```
  * more than ```5000ms``` RT

**Comment by sosna** [comment]
This happens in off-line mode

**Comment by Tzaphkiel** [comment]
Care to expand on this ?
Is it happening because of a connection timeout when the job is trying to access the endpoint ? 
Is that what has been replicated in 'off-line mode'?

**Comment by sosna** [comment]
The issue has not been fully fixed, as there is another instance a bit below (on line 109).
