### ISSUE TITLE
Performance of Events list display

### ISSUE THREAD

**Issue by Tzaphkiel** [ecbsdmx/milliws#8]
Displaying the ```Events``` view takes a very long time (with the loading spinner spinning away).

Tracking the web interface and ```htop``` on the server when the view is accessed, shows the following:
  * very little or no ```mongod``` activity: up to 47% CPU from time to time
  * 1 of 2 CPU pushed to 100% by ```node main.js```process most of the time it takes for the view to display the table
  * there are ~550 000 (only?!) events
  * the scheduler is active but jobs have been paused
 
Paging through the table has:
  * ```mongod``` use 100% of the CPU (1, 2 or both CPUs) 
  * whereas this time, the ```node main.js``` process is hardly solicited (~5%)

**Comment by Tzaphkiel** [comment]
The closing of issue #9 has already helped with the performances but only, it seems, when ```node``` has loaded the whole collection...
The initial view load takes has ```mongodb``` using an average amount of CPU for a short while and than ```node``` uses still uses 100%CPU for some time with hardly 1% CPU for ```mongodb``` process anymore...!
Once displayed, it is rather smooth.

Some meteor profiling might help.

**Comment by sosna** [comment]
Solved with issue #9
